language: node_js
node_js:
  - 10
script:
  - npx docz build
  - cp .docz/dist/index.html .docz/dist/404.html
deploy:
  local_dir: .docz/dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master