sudo: false
language: node_js
node_js:
  - 12
cache: npm
branches:
  only:
    - src
script:
  - npx docz build
deploy:
  local_dir: .docz/dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: src
